# 共有8个级别，按照从低到高为：ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF。

Configuration:
  status: warn # log4j2框架本身的日志级别
  monitorInterval: 30 # log4j2重新扫描加载配置文件的周期单位秒，这里表示间隔30s重新加载配置文件

  Properties: # 定义全局变量
    Property: # 缺省配置（用于开发环境）。其他环境需要在VM参数中指定，如下：
      - name: log.level.console
        value: info
      - name: log.path
        value: ../log
      - name: app.name
        value: mosaic
      - name: log.pattern
        value: "%-d{yyyy-MM-dd HH:mm:ss.SSS} [%p]  [%t]  %m @%F:%L%n"



  Appenders:
    Console:  #输出到控制台
      name: CONSOLE
      target: SYSTEM_OUT
      PatternLayout:
        pattern: ${log.pattern}
    #  启动日志

    RollingFile:
      - name: ROLLING_FILE
        fileName: ${log.path}/${app.name}.log
        filePattern: "${log.path}/archive/${app.name}.%d{yyyy-MM-dd}.log.gz"
        PatternLayout:
          pattern: ${log.pattern}
        Filters:
          # 一定要先去除不接受的日志级别，然后获取需要接受的日志级别
          ThresholdFilter:
            - level: debug
              onMatch: ACCEPT
              onMismatch: DENY
        Policies:
          TimeBasedTriggeringPolicy:  # 按天分类
            modulate: true
            interval: 1
        DefaultRolloverStrategy:
          Delete:
            basePath: "${log.path}/archive/"
            maxDepth: 3
            IfFileName:
              glob: "*.log.gz"
            IfLastModified:
              age: 7d

      #   错误日志
      - name: EXCEPTION_ROLLING_FILE
        ignoreExceptions: false
        fileName: ${log.path}/${app.name}-error.log
        filePattern: "${log.path}/archive/${app.name}-error.%d{yyyy-MM-dd}.log.gz"
        ThresholdFilter:
          level: error
          onMatch: ACCEPT
          onMismatch: DENY
        PatternLayout:
          pattern: ${log.pattern}
        Policies:
          TimeBasedTriggeringPolicy:  # 按天分类
            modulate: true
            interval: 1
        DefaultRolloverStrategy:     # 文件最多100个
          max: 100


  Loggers:
    AsyncRoot:
      additivity: true
      level: info
      includeLocation: true
      AppenderRef:
        - ref: CONSOLE
        - ref: ROLLING_FILE
        - ref: EXCEPTION_ROLLING_FILE





